### PR TITLE
Snap 347 - Make application settings editable from the UI screen

### PR DESCRIPTION
**Pull request by iradaik**

### CODE REVIEW

**Comment by rabay108** [comment]
LGTM

**Comment by kmcgrath** [comment]
TravisCI build is failing, please investigate.

**Comment by rabay108** [comment]
LGTM

**Comment by kmcgrath** [comment]
LGTM

**Comment by kmcgrath** [comment]
Please resolve conflicts from issue #41

**Comment by iradaik** [comment]
SNAP-338 was merged with SNAP-347 since pull request fro 338 was merged first with develop we do not need current pull request any more. I will close it

**Pull request closed without merging**
