### PR TITLE
Add separate logout controller and remove blinking pages on state changes

### PR DESCRIPTION
**Pull request by iradaik**

### CODE REVIEW

**Comment by rabay108** [comment]
LGTM

**Comment by rabay108** [comment]
@iradaik @Andrey-Vasilenko can you please check this branch is out of date with base branch ?

**Comment by iradaik** [comment]
@rabay108, done

**Comment by rabay108** [comment]
LGTM

**Comment by rabay108** [comment]
LGTM

**Comment by rabay108** [comment]
LGTM

**Comment by rabay108** [comment]
LGTM

**Pull request merged**
