### PR TITLE
Added deploy ami script

### PR DESCRIPTION
**Pull request by ykyr**
SNAP-331
As a Developer I want to have build script to deploy to all the regions automatically.

### CODE REVIEW

**Comment by rabay108** [comment]
LGTM

**Comment by ykyr** [comment]
Abay, I just got an idea, and rewrote a deploy script. Removed 2nd parameter to simplify usage. Now source region will be setted automatically.

**Comment by rabay108** [comment]
LGTM

**Comment by rabay108** [comment]
LGTM

**Pull request merged**
